### ISSUE TITLE
required assets

### ISSUE THREAD

**Issue by pmp-p** [fireclawthefox/DirectGuiExtension#2]
That library may require assets that are only installed with a Panda3D distribution and with a correct Prc. That may lead to runtime error since assets are not checked on startup.

eg https://github.com/fireclawthefox/DirectGuiExtension/blob/e6fe8bb84b738b5ab57c170d1e58665fcf390481/DirectGuiExtension/DirectSpinBox.py#L139

on android and browser - where runtime is per application - the full distribution is not usually available.

**Comment by fireclawthefox** [comment]
One other place that contains assets from the engine is here:

https://github.com/fireclawthefox/DirectGuiExtension/blob/e6fe8bb84b738b5ab57c170d1e58665fcf390481/DirectGuiExtension/DirectTreeView.py#L23-L24
